"""
Copyright  (c)  2018-2024 Open Text  or  one  of its
affiliates.  Licensed  under  the   Apache  License,
Version 2.0 (the  "License"); You  may  not use this
file except in compliance with the License.

You may obtain a copy of the License at:
http://www.apache.org/licenses/LICENSE-2.0

Unless  required  by applicable  law or  agreed to in
writing, software  distributed  under the  License is
distributed on an  "AS IS" BASIS,  WITHOUT WARRANTIES
OR CONDITIONS OF ANY KIND, either express or implied.
See the  License for the specific  language governing
permissions and limitations under the License.
"""
REL_TOLERANCE = 1e-6
ABS_TOLERANCE = 1e-12

rel_abs_tol_map = {
    "RandomForestRegressor": {
        "explained_variance": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "rmse": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        **dict.fromkeys(["r2", "R-squared"], {"rel": 1e-01, "abs": ABS_TOLERANCE}),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": 1e-01, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "bic": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "f": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-02, "abs": ABS_TOLERANCE},
    },
    "RandomForestClassifier": {
        "auc": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "prc_auc": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "accuracy": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "log_loss": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "precision": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "recall": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "f1_score": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "mcc": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "markedness": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "csi": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "confusion_matrix": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "cutoff_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "lift_chart": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "prc_curve": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "predict_proba": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "roc_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "score": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-00, "abs": ABS_TOLERANCE},
    },
    "DecisionTreeRegressor": {
        "explained_variance": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "rmse": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        **dict.fromkeys(["r2", "R-squared"], {"rel": 1e-00, "abs": ABS_TOLERANCE}),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": 1e-00, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "bic": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "f": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-02, "abs": ABS_TOLERANCE},
    },
    "DecisionTreeClassifier": {
        "auc": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "prc_auc": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "accuracy": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "log_loss": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "precision": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "recall": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "f1_score": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "mcc": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "markedness": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "csi": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "confusion_matrix": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "cutoff_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "lift_chart": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "prc_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict_proba": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "roc_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "score": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "to_python": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-00, "abs": ABS_TOLERANCE},
    },
    "DummyTreeRegressor": {
        "explained_variance": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "rmse": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        **dict.fromkeys(
            ["r2", "R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "bic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "f": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-01, "abs": ABS_TOLERANCE},
    },
    "DummyTreeClassifier": {
        "auc": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "prc_auc": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "accuracy": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "log_loss": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "precision": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "recall": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "f1_score": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mcc": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "markedness": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "csi": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "confusion_matrix": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "cutoff_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "lift_chart": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "prc_curve": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "predict_proba": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "roc_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "score": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-01, "abs": ABS_TOLERANCE},
    },
    "XGBRegressor": {
        "explained_variance": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "rmse": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        **dict.fromkeys(["r2", "R-squared"], {"rel": 1e-00, "abs": ABS_TOLERANCE}),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": 1e-00, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "bic": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "f": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "to_json": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-01, "abs": ABS_TOLERANCE},
    },
    "XGBClassifier": {
        "auc": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "prc_auc": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "accuracy": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "log_loss": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "precision": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "recall": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "f1_score": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "mcc": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "markedness": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "csi": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "confusion_matrix": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "cutoff_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "lift_chart": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "prc_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict_proba": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "roc_curve": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "to_json": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "score": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-00, "abs": ABS_TOLERANCE},
    },
    "Ridge": {
        "explained_variance": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "rmse": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        **dict.fromkeys(
            ["r2", "R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "bic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "f": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "predict": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
    },
    "Lasso": {
        "explained_variance": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "max_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "rmse": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        **dict.fromkeys(
            ["r2", "R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "bic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": REL_TOLERANCE, "abs": 1e-09},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "f": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "predict": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
    },
    "ElasticNet": {
        "explained_variance": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "max_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "rmse": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        **dict.fromkeys(
            ["r2", "R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "bic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": REL_TOLERANCE, "abs": 1e-09},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "f": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "predict": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
    },
    "LinearRegression": {
        "explained_variance": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "max_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "rmse": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        **dict.fromkeys(
            ["r2", "R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "bic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "f": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "predict": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
    },
    "LinearSVR": {
        "explained_variance": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "max_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "rmse": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        **dict.fromkeys(
            ["r2", "R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "bic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "f": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "score": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "predict": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": 1e-01, "abs": ABS_TOLERANCE},
    },
    "PoissonRegressor": {
        "explained_variance": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "rmse": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        **dict.fromkeys(["r2", "R-squared"], {"rel": 1e-05, "abs": ABS_TOLERANCE}),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": 1e-05, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "bic": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "F-statistic": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "Prob (F-statistic)": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "Kurtosis": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "Skewness": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "Jarque-Bera (JB)": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "df": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "ss": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "ms": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "f": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "p_value": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "coef_": {"rel": 1e-03, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "score": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "to_python": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "load_model": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
    },
    "AR": {
        "explained_variance": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "rmse": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        **dict.fromkeys(["r2", "R-squared"], {"rel": 1e-03, "abs": ABS_TOLERANCE}),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": 1e-03, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "bic": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "phi_": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mse_": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-01, "abs": ABS_TOLERANCE},
    },
    "MA": {
        "explained_variance": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "rmse": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        **dict.fromkeys(["r2", "R-squared"], {"rel": 1e-01, "abs": ABS_TOLERANCE}),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": 1e-01, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "bic": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "phi_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mse_": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-01, "abs": ABS_TOLERANCE},
    },
    "ARMA": {
        "explained_variance": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-05, "abs": ABS_TOLERANCE},
        "rmse": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        **dict.fromkeys(
            ["r2", "R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "bic": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "phi_": {"rel": 1e-04, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mse_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-02, "abs": ABS_TOLERANCE},
    },
    "ARIMA": {
        "explained_variance": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "max_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "median_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_absolute_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "mean_squared_error": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "mean_squared_log_error": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "rmse": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        **dict.fromkeys(["r2", "R-squared"], {"rel": 1e-03, "abs": ABS_TOLERANCE}),
        **dict.fromkeys(
            ["r2_adj", "Adj. R-squared"], {"rel": 1e-03, "abs": ABS_TOLERANCE}
        ),
        "aic": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "bic": {"rel": 1e-01, "abs": ABS_TOLERANCE},
        "phi_": {"rel": 1e-00, "abs": ABS_TOLERANCE},
        "intercept_": {"rel": REL_TOLERANCE, "abs": ABS_TOLERANCE},
        "mse_": {"rel": 1e-02, "abs": ABS_TOLERANCE},
        "predict": {"rel": 1e-01, "abs": ABS_TOLERANCE},
    },
    "TENSORFLOW": REL_TOLERANCE,
    "TFIDF": 1e-01,
}
